### ISSUE TITLE
CMD Issue? **TypeError: sequence item 0: expected str instance, int found**

### ISSUE THREAD

**Issue by kanyeah** [Smidelis/discord-link-opener#12]
When I run open.py I get this message, last row error...any idea how to solve it? Thanks.

[INFO]  USER#1234 is ready to watch for links.
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User123\Desktop\discord-link-opener-master\open.py", line 116, in on_ready
    print_time('Watching for keywords {}.'.format(', '.join(keywords)))
**TypeError: sequence item 0: expected str instance, int found**

**Comment by notpudie** [comment]
I changed the line
print_time('Watching for keywords {}.'.format(', '.join(keywords)))
to
print_time('Watching for keywords {}.'.format(', '.join(map(str, keywords))))
and that fixed the error for me.

**Comment by devNostyle** [comment]
solved but another problem come when link should be opened :

```
Task exception was never retrieved
future: <Task finished coro=<check_urls() done, defined at C:\Users\xx\Desktop\chrome\open.py:93> exception=TypeError("'in <string>' requires string as left operand, not int")>
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\chrome\open.py", line 95, in check_urls
    if any(x in url.lower() for x in keywords) and all(x not in url.lower() for x in blacklist):
  File "C:\Users\xxx\Desktop\chrome\open.py", line 95, in <genexpr>
    if any(x in url.lower() for x in keywords) and all(x not in url.lower() for x in blacklist):
TypeError: 'in <string>' requires string as left operand, not int
```

> I changed the line
> print_time('Watching for keywords {}.'.format(', '.join(keywords)))
> to
> print_time('Watching for keywords {}.'.format(', '.join(map(str, keywords))))
> and that fixed the error for me.
